### ISSUE TITLE
[Linux Debian] Typing in TPTMP's console produces no characters or scrambled ones if you hold CTRL+Letter

### ISSUE THREAD

**Issue by MoodyKSA** [cracker64/tptmp#19]
I can type fine on TPT's native console. However, typing on TPTMP's console is very buggy. I can't type anything. But some how I can manage to work around that by holding CTRL but it will still produce very buggy results.

How to produce: Open TPTMP's console -> type anything in it. Result: no character written

Solution: Play TPT under wine or windows virtualbox

**Comment by jacob1** [comment]
Which version of TPT are you using? The current release version is 93.3, but it sounds like you are using the latest compiled source.

If you self-compiled it, you should compile the [stable](https://github.com/ThePowderToy/The-Powder-Toy/commits/stable) branch instead if you want tptmp support.

tptmp support is actually one of the reasons 94.0 hasn't been released yet. The keyboard event doesn't work anymore because I upgraded to SDL2. I need to redo that event and then all scripts which use keyboard input will need to update.

**Comment by MoodyKSA** [comment]
I self-compiled it myself (v93.3)
Thank you. Downloading it from the website works fine

**Comment by jacob1** [comment]
Fixed in tptmp version 0.100
