### ISSUE TITLE
limitation of scale

### ISSUE THREAD

**Issue by ghost** [cracker64/tptmp#35]
Limited scale of mouse for preventing users to literally crush world and tptmp, may be automatically applied to lobby and setting for private servers.

**Comment by LBPHacker** [comment]
We do not currently plan on adding lag prevention to TPTMP. The server is not affected by laggy changes made to the simulation, and client-side lag is way too difficult to prevent.

Limiting brush scale is a simple fix, but it doesn't prevent lag from other sources and is annoying when you do in fact want a big brush, so the disadvantages outweigh the advantages. Many such simple measures fall into this category and are thus ruled out.

Rather than apply annoying half-fixes, we recommend that you choose well who you play with. If you have no choice, for example if people lag the main lobby, you can always join a different room, or in radical cases, report offenders.
